spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: StockX
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}
#  docker:
#    compose:
#      lifecycle-management: start_only